djangoapp/blog/urls.py
from django.urls import path
from blog.views import PostListView, CreatedByListView, CategoryListView, TagListView, SearchListView, PageDetailView, PostDetailView

app_name = "blog"

urlpatterns = [
    path('', PostListView.as_view(), name="index"),
    path('post/<slug:slug>/', PostDetailView.as_view(), name="post"),
    path('page/<slug:slug>/', PageDetailView.as_view(), name="page"),
    path('created_by/<int:author_pk>/', CreatedByListView.as_view(), name="created_by"),
    path('category/<slug:slug>/', CategoryListView.as_view(), name="category"),
    path('tag/<slug:slug>/', TagListView.as_view(), name="tag"),
    path('search/', SearchListView.as_view(), name="search"),
]

djangoapp/project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include("blog.urls")),
    path('summernote/', include('django_summernote.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djangoapp/blog/models.py
from django.db import models
from django.urls import reverse
from utils.rands import new_slugfy
from django.contrib.auth.models import User
from utils.images import resize_image
from django_summernote.models import AbstractAttachment

class PostAttachment(AbstractAttachment):
    def save(self, *args, **kwargs):
        if not self.name:
            self.name = self.file.name
        
        current_file_name = str(self.file.name)
        super_save = super().save(*args, **kwargs)
        file_changed = False

        if self.file:
            file_changed = current_file_name != self.file.name
        
        if file_changed:
            resize_image(self.file, 900, quality=100)
        
        return super_save


class Tag(models.Model):
    class Meta:
        verbose_name = "Tag"
        verbose_name_plural = "Tags"

    name = models.CharField(max_length=80)
    slug = models.SlugField(
        unique=True,
        max_length=90,
        blank=True,
        default="",
        null=True,
    )

    def save(self, *args, **kwargs) -> None:
        if not self.slug:
            self.slug = new_slugfy(self.name, 3)
        return super().save( *args, **kwargs)
    
    def __str__(self) -> str:
        return self.name


class Category(models.Model):
    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"

    name = models.CharField(max_length=80)
    slug = models.SlugField(
        unique=True,
        max_length=90,
        blank=True,
        default="",
        null=True,
    )
    
    def save(self, *args, **kwargs) -> None:
        if not self.slug:
            self.slug = new_slugfy(self.name, 3)
        return super().save( *args, **kwargs)
    
    def __str__(self) -> str:
        return self.name


class PostManager(models.Manager):
    def get_published(self):
        return self.filter(is_published=True).order_by("-pk")


class Page(models.Model):
    class Meta:
        verbose_name = "Page"
        verbose_name_plural = "Pages"
    
    objects = PostManager()

    title = models.CharField(max_length=80)
    slug = models.SlugField(
        unique=True,
        max_length=90,
        blank=True,
        default="",
        null=True,
    )
    is_published = models.BooleanField(
        default=False,
        help_text="This field needs to be checked for the page to be published."
    )
    content = models.TextField()

    def get_absolute_url(self):
        if not self.is_published:
            return reverse("blog:index")
        return reverse("blog:page", kwargs={"slug": self.slug}) 
    
    def save(self, *args, **kwargs) -> None:
        if not self.slug:
            self.slug = new_slugfy(self.title, 3)
        return super().save( *args, **kwargs)
    
    def __str__(self) -> str:
        return self.title


class Post(models.Model):
    class Meta:
        verbose_name = "Post"
        verbose_name_plural = "Posts"

    objects = PostManager()

    title = models.CharField(max_length=90)
    slug = models.SlugField(
        unique=True,
        max_length=120,
        blank=True,
        default="",
        null=True,
    )
    excerpt = models.CharField(max_length=150)
    is_published = models.BooleanField(
        default=False,
        help_text="This field needs to be checked for the post to be published."
    )
    content = models.TextField()
    # post cover
    cover = models.ImageField(
        upload_to="posts/%Y/%m/",
        blank=True,
        default="",
    )
    cover_in_post_content = models.BooleanField(
        default=True,
        help_text="If checked, it will display the cover within the post.",
    )
    created_at = models.DateField(auto_now_add=True,)
    updated_at = models.DateField(auto_now=True,)
    created_by = models.ForeignKey(
        User, 
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name="created_by",  # user.post_created_by.all
    )
    updated_by = models.ForeignKey(
        User, 
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name="updated_by",  # user.post_updated_by.all
    )
    category = models.ForeignKey(
        Category, 
        on_delete=models.SET_NULL, 
        null=True, 
        blank=True, 
        default="",
    )
    tags = models.ManyToManyField(
        Tag,
        blank=True,
        default="",
    )

    def get_absolute_url(self):
        if not self.is_published:
            return reverse("blog:index")
        return reverse("blog:post", kwargs={"slug": self.slug})    
    
    def save(self, *args, **kwargs) -> None:
        if not self.slug:
            self.slug = new_slugfy(self.title, 3)

        current_cover_name = str(self.cover.name)
        super_save = super().save(*args, **kwargs)
        cover_changed = False

        if self.cover:
            cover_changed = current_cover_name != self.cover.name

        if cover_changed:
            resize_image(self.cover, 900, quality=100)

        return super_save
    
    def __str__(self) -> str:
        return self.title

djangoapp/blog/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import redirect
from django.db.models import Q
from django.contrib.auth.models import User
from django.http import Http404, HttpRequest, HttpResponse
from django.views.generic import ListView, DetailView
from blog.models import Post, Page

PER_PAGE = 9

class PostListView(ListView):
    template_name = "blog/pages/index.html"
    context_object_name = "posts"
    paginate_by = PER_PAGE
    queryset = Post.objects.get_published()

    # overriding the get_context_data() of ListView()
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context.update({
            "page_title": "Home - "
        })
        return context


class PostDetailView(DetailView):
    template_name = "blog/pages/post.html"
    queryset = Post.objects.get_published()

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context["page_title"] = f"{self.object.title} Post - "
        return context


class PageDetailView(DetailView):
    template_name = "blog/pages/page.html"
    queryset = Page.objects.get_published()

    def get_context_data(self, **kwargs) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context["page_title"] = f"{self.object.title} Page - "
        return context
    

class CreatedByListView(PostListView):
    def __init__(self, **kwargs: Any) -> None:
        super().__init__(**kwargs)
        self._temp_context: dict[str, Any] = {}

    def get(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        author_pk = self.kwargs.get("author_pk")
        user = User.objects.filter(pk=author_pk).first()

        if user is None:
            raise Http404
        
        self._temp_context.update(
            {
                "author_pk": author_pk,
                "user": user,
            }
        )
        
        return super().get(request, *args, **kwargs)
    
    def get_queryset(self) -> QuerySet[Any]:
        qs = super().get_queryset()
        qs = qs.filter(created_by__pk=self._temp_context["user"].pk)
        return qs
    
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        user = self._temp_context["user"]
        user_full_name = user.username

        if user.first_name:
            user_full_name = f"{user.first_name} {user.last_name} "
        
        page_title = f"Posts by {user_full_name} - "
        context.update(
            {
                "page_title": page_title,
            }
        )

        return context


class CategoryListView(PostListView):
    allow_empty = False

    def get_queryset(self) -> QuerySet[Any]:
        qs = super().get_queryset().filter(category__slug=self.kwargs.get("slug"))
        return qs
    
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        page_title = f"{self.object_list[0].category} Category - "
        context.update(
            {
                "page_title": page_title,
            }
        )
        return context


class TagListView(PostListView):
    allow_empty = False

    def get_queryset(self) -> QuerySet[Any]:
        return super().get_queryset().filter(tags__slug=self.kwargs.get("slug"))
    
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        tag_slug = self.kwargs.get("slug")
        tag_name = self.object_list[0].tags.filter(slug=tag_slug).first()
        page_title = f"{tag_name} Tag - "
        context.update(
            {
                "page_title": page_title,
            }
        )
        return context


class SearchListView(PostListView):
    def __init__(self, **kwargs: Any) -> None:
        super().__init__(**kwargs)
        self._search_value = ""

    def setup(self, request: HttpRequest, *args: Any, **kwargs: Any) -> None:
        self._search_value = request.GET.get("search", "").strip()
        return super().setup(request, *args, **kwargs)

    def get(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        if self._search_value == "":
            return redirect("blog:index")
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        qs = super().get_queryset().filter(
            Q(title__icontains=self._search_value) |
            Q(excerpt__icontains=self._search_value) | 
            Q(content__icontains=self._search_value)
        )[:PER_PAGE]
        return qs
    
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        page_title = f"{self._search_value} - "
        context.update(
            {
                "search_value": self._search_value,
                "page_title": page_title,
            }
        )
        return context

djangoapp/blog/templates/blog/pages/index.html
{% extends "blog/base.html" %}

{% block content %}
    <main class="main-content section-wrapper">
        <div class="section-content-wide">
            <div class="section-gap">

                {% if posts %}
                    <div class="card-grid">
                        {% for post in posts %}
                            {% include "blog/partials/_post-card.html" with i=forloop.counter0 %}
                        {% endfor %}
                </div>
                {% else %}
                    <div class="not-found center">
                        <h1>Page Not Found 😔</h1>
                        <p>I didn't find the link, please go to other page or go <a href="{% url "blog:index" %}">Home</a>!</p>
                    </div>
                {% endif %}
            </div>
        </div>
    </main>
{% endblock content %}

djangoapp/blog/templates/blog/pages/page.html
{% extends "blog/base.html" %}

{% block content %}
    <main class="main-content section-wrapper">
        <div class="section-content-narrow">
            <div class="section-gap">
                <h1 class="center">{{ page.title }}</h1>
                {{ page.content|safe }}
            </div>
        </div>
    </main>
{% endblock content %}

djangoapp/blog/templates/blog/pages/post.html
{% extends "blog/base.html" %}

{% block additional_head %}
{% comment %} CodeMirror {% endcomment %}
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.62.2/codemirror.min.css">
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/codemirror/6.65.7/theme/dracula.min.css">

<script src="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.62.2/codemirror.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.62.2/mode/python/python.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.62.2/mode/javascript/javascript.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.62.2/mode/htmlmixed/htmlmixed.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.62.2/mode/css/css.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.62.2/mode/xml/xml.min.js"></script>
{% endblock additional_head %}

{% block content %}
    <main class="main-content single-post section-wrapper">
        <div class="singe-post-content section-content-narrow">
            <div class="single-post-gap section-gap">

                {% if post.cover and post.cover_in_post_content %}
                    <div class="single-post-cover pb-base">
                        <img src="{{ post.cover.url }}" alt="{{ post.title }}" loading="lazy">
                    </div>
                {% endif %}

                <h2 class="single-post-title pb-base center">
                    {{ post.title }}
                </h2>

                <div class="post-meta pb-base">
                    <div class="post-meta-item">
                        <a href="{% url "blog:created_by" post.created_by.pk %}" class="post-met-link">
                            <i class="fa-solid fa-user"></i>
                            <span>
                                {% if post.created_by.first_name %}
                                    {{ post.created_by.first_name }} {{ post.created_by.last_name }}
                                {% else %}
                                    {{ post.created_by.username }}
                                {% endif %}
                            </span>
                        </a>
                    </div>
                    <div class="post-meta-item">
                        <span class="post-meta-link">
                            <i class="fa-solid fa-calendar-days"></i>
                            <span>
                                {{ post.created_at}} {{post.created_at|time:"H:i"}}
                            </span>
                        </span>
                    </div>
                    {% if post.category %}
                        <div class="post-meta-item">
                            <a href="{% url "blog:category" post.category.slug %}" class="post-meta-link">
                                <i class="fa-solid fa-tag"></i>
                                <span>
                                    {{ post.category }}
                                </span>
                            </a>
                        </div>
                    {% endif %}
                </div>

                <p class="single-post-excerpt pb-base">
                    {{ post.excerpt|safe }}
                </p>

                <div class="separator"></div>

                <div class="single-post-content">
                    {{ post.content|safe }}

                    {% if post.tags.exists %}
                        <div class="post-tags">
                            <span>Tags: </span>

                            {% for tag in post.tags.all %}
                                <a class="post-tag-link"  href="{% url "blog:tag" tag.slug %}">
                                    <i class="fa-solid fa-link"></i>
                                    <span>{{ tag }}</span>
                                </a>
                            {% endfor %}
                        </div>
                    {% endif %}

                </div>
            </div>
        </div>
    </main>
{% endblock content %}